apiVersion: v2
name: krateo-sse-proxy
description: >-
  Krateo SSE proxy. Polls ClickHouse and pushes new K8s events to connected
  browsers via Server-Sent Events.
type: application
version: 0.1.10
appVersion: "1.1.4"
home: https://krateo.io
icon: https://github.com/krateoplatformops/krateo/blob/main/docs/media/logo.svg
keywords:
  - krateo
  - platformops
  - sse
  - observability
sources:
  - https://github.com/krateo-platformops/clickstack-chart
  - https://github.com/krateo-platformops/sse-proxy
