apiVersion: v1
kind: Service
metadata:
  name: {{ include "krateo-sse-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "krateo-sse-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "krateo-sse-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
